### ISSUE TITLE
Terminos y condiciones

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Geofencing#50]
Agregar el link para mostrar los terminos y condiciones de la aplicacion

**Comment by gusanchez** [comment]
Utiliza el mismo web service de registro de usuario. Parametro terminos

**Comment by KleyvertDevelop** [comment]
@gusanchez Man puedes colocar un ejemplo del servicio registro con el parámetro terminos, el nombre del parámetro se pasa por el Header o por la URL o se le agrega al JSON request?, también mandame la URL para mostrar los términos y condiciones.

**Comment by gusanchez** [comment]
@KleyvertDevelop aqui esta el ejemplo del json que deberia mandarse con el parametro terminos:true si acepto las condiciones, si no se regresa al home y se resetea todo, si no acepta los terminos no puede seguir adelante

 {
 "nombre": "Kleyvert",
 "apellido": "Martinez",
 "email": "kleymaster@gmail.com",
 "nacimiento": "1988-04-14",
 "telefono": null,
 "sexo": "Hombre",
 "direccion": null,
 "nombreUsuario": "kleymaster@gmail.com",
 "clave": "100210350375524102",
 "idFacebook": null,
 "idGoogle": "100210350375524102",
 "session": true,
 "favoritos": false,
 "notificaciones": true,
 "terminos": true
}

http://flyermob.com/terminos.html aqui esta el  link de los terminos
