### ISSUE TITLE
Filtrado de intereses - Perfil

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Geofencing#55]
Agregar filtrado de promos que quieres recibir en el Perfil, por ejemplo: solo quiero recibir promos de zapatos y comida.

**Comment by gusanchez** [comment]
- [x] Para obtener el listado de todas las categorias se hace la peticion al web service:

GET                /categoria

el lista todas las categorias Padres y los Hijos, las categorias padres vienen con el valor padre:0

- [x] Web service para enviar las preferencias:

POST          /usuario/categoria?usuario_id=165&cat_list=1,2,3,6
Parametros: 
- Id de usuario
- lista de ids de categorias seleccionadas: 1,2,5,8,9,20. Lista String separados por comas sin espacios.
Respuesta: json ok con el mensaje: Su preferencia se ha guardado exitosamente

- [x] Web Service para actualizar las categorias

PUT           /usuario/categoria/update?usuario_id=165&cat_list=1,2,3,6
Parametros: 
- Id de usuario
- lista de ids de categorias seleccionadas: 1,2,5,8,9,20. Lista String separados por comas sin espacios.
Respuesta: json ok con el mensaje: Su preferencia se ha guardado exitosamente

**Validar que si se selecciona solo el padre que tambien se selecciones todos los hijos de ese padre, es decir, no puede seleccionar solo el padre**

En caso de algun error devuelve el mensaje: Se produjo un error, vuelva a intentarlo

**Comment by gusanchez** [comment]
***Pasar esta funcionalidad a la pantalla de Ajustes***

**Comment by gusanchez** [comment]
Metodo para obtener las categorias seleccionadas por usuario

GET
/categoria/usuario?id=152

Parametro:

- Id de usuario

Retorna la lista de categorias que ese usuario tiene seleccionadas

**Comment by KleyvertDevelop** [comment]
@gusanchez pasame un ejemplo o el print de postman para este servicio por fa:

PUT /usuario/categoria/update

A este servicio también se le debe pasar un body pero del tipo "form-data" ??
