### ISSUE TITLE
Contabilizar compartir

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Geofencing#63]
Contabilizar la cantidad de compartir en la app, buscar si se puede hacer detallado por red social. 

Se crea un web service que maneja los dos casos:
- [x] Enviar el Id de Usuario para contabilizar las invitaciones para descargar
- [x] Enviar el Id de Usuario y Id Promo para contabilizar las veces que una promo es compartida

**Comment by gusanchez** [comment]
- [ ] Web Service para contabilizar las invitaciones para compartir:
La idea de esta funcionalidad es que se pase el link de descarga de la tienda de Google Play

`https://play.google.com/store/apps/details?id=com.octagon.flyermob`

POST
`http://138.219.42.79:9000/compartirApp?id=152`

- Recibe el id de usuario
- Retorna el objeto usuario:
`{"id":152,"nombre":"Gustavo","apellido":"Sanchez","email":"gusadolfo@gmail.com","nacimiento":"1982-02-16 15:33:38.0","telefono":null,"sexo":"M","direccion":null,"nombreUsuario":"gusadolfo","clave":"clave","idFacebook":null,"idGoogle":null,"session":true,"favoritos":true,"notificaciones":true,"confirmacion":null,"compartir":2}`

- [ ] Web Service para contabilizar las promos compartidas:

La idea de esta funcionalidad es que se comparta la imagen de la promo y el link de Google Play para descargar la app:

`https://play.google.com/store/apps/details?id=com.octagon.flyermob`

POST
`/compartirPromo `

- Recibe el id de usuario
- Recibe el id de la promo

Retorna el objeto CompartirPromo:

`{"id":5,"idUsuario":152,"idPromo":11,"fecha":"2017/02/16 18:12:05"}`

**Comment by KleyvertDevelop** [comment]
@gusanchez Man una pregunta, en el servicio /compartirPromo, los parámetros se envian en un JSON request o van en la URL?

**Comment by gusanchez** [comment]
Los parametros idUsuario y idPromo se envia en form-data igual que en Ubicacion y Registro
