### ISSUE TITLE
Obtener Promo por prefiltrado de categoria

### ISSUE THREAD

**Issue by victorinox88** [gusanchez/Geofencing#84]
Dado un usuario obtener las promo dependiendo de las categorias seleccionadas por el usuario. getPromoFilteredByCategory(idUsuario), hay q validar tanto padres como a los hijos

**Comment by gusanchez** [comment]
Modificar y agregar las categorias del usuario en:

Metodos que retornan Categoria: Aqui solo habria que hacer el chequeo de las categorias que estan en Categoria_Usuario
- [x] GET           /categoria                        controllers.CategoriaController.list()
- [x] GET           /categoria/padre                controllers.CategoriaController.getParentCategory()
- [x] GET           /categoria/hijo                   controllers.CategoriaController.getCategoryByParent(id: Integer, coordX: String, coordY: String) ESTE ES EL QUE HAY QUE PASAR A PROMO CONTROLLER
- [x] GET           /categoria/usuario                controllers.CategoriaController.getCategoryByUser(id: Integer)

Metodos que retornan Promo: En estos es donde iria el metodo nuevo que hiciste
- [x] GET           /promo/categoria                  controllers.PromoController.getPromoByCategory(id: Integer)
- [ ] GET           /promo/categoria-por-padre        controllers.PromoController.getPromoByCategoryByParent(id: Integer)

- [ ] POST          /ubicacion                        controllers.UbicacionController.create() agregar las categorias del usuario

**Comment by gusanchez** [comment]
Tambien agregar la validacion de si el usuario tiene habilitadas las notificaciones o no, revisar en la tabla Usuario el campo "notificaciones" para el metodo:

POST /ubicacion controllers.UbicacionController.create()

***PASADO AL TICKET #66***

**Comment by gusanchez** [comment]
@victorinox88 revisar:

GET /promo/categoria controllers.PromoController.getPromoByCategory(id: Integer)

Ahora que tiene el idUser, pero si el usuario no tiene ningun registro en Categoria_Usuario deberia traer todas las promos que hay en la categoria que le paso

***Ademas agrega que si el id de la categoria que le pasa sea 0 que devuelva todas las promos de la categoria padre*** esto es para cuando se cargue esa pantalla el combo con las categorias no venga con alguna subcategorias seleccionada por defecto y muestre todas las promociones que tiene esa categoria padre
