### ISSUE TITLE
Cambiar getCategoryByParent

### ISSUE THREAD

**Issue by gusanchez** [gusanchez/Geofencing#85]
- [x] Cambiar getCategoryByParent y dejarlo para que retorne la categoria por padre.
- [x] mover el fetchPromosSucursal a PromoController y crear getPromoByCategoryByParentBySucursal que reciba coordX, coordY, categoria id

**Comment by victorinox88** [comment]
pr:https://bitbucket.org/octagontech/flyermob_ws/pull-requests/3/se-modifico-cambiar-getcategorybyparent-y/diff
